### ISSUE TITLE
ModuleNotFoundError: No module named 'grepfunc'

### ISSUE THREAD

**Issue by MohammedZidane** [claassenlab/S3-CIMA#1]
Hi,
I cannot find the grepfunc module.

Could you help?
Thanks!

**Comment by sepidehbabaei** [comment]
you can install it via pip:  https://pypi.org/project/grepfunc/

The grep function is used to find the markers in the data. If you know the index of the markers (index of the columns of the data representing markers, you dont need grep:

inx = np.asarray(grep(cols, "Cyc" , n=True))
markers = inx[:,1].tolist()
inx = inx [:,0].astype(int)

**Comment by MohammedZidane** [comment]
okay thanks :)
